### ISSUE TITLE
TimeSketch

### ISSUE THREAD

**Issue by neorage2k3** [rough007/CCF-VM#2]
When analysing a new timeline or existing timeline in TimeSketch, TimeSketch shows no data and a pop up "Internal Server Error"

**Comment by rough007** [comment]
Try restarting TimeSketch by checking the processes started in /etc/rc.local or rebooting the VM will effectively restart them

**Comment by rough007** [comment]
The issue was with a corrupt TimeSketch database and some other issues that are now fixed in v2.1 (now released)
