### ISSUE TITLE
No such file or directory log2timeline.py

### ISSUE THREAD

**Issue by glennbarrett** [rough007/CCF-VM#3]
On a fresh install of CCF_VM 2.2, I am getting an error that there is no such file or directory for log2timeline.py when running the standard cdqr.py command to process a windows zip from CyLR.  It looks like the new TimeSketch options aren't part of the documentation, so maybe this command or process has changed somehow but isn't documented?

>cdqr@CCF_VM:~$ cdqr.py HOSTNAME.zip -p win --max_cpu -z --es_kb HOSTNAME
CDQR Version: 4.0.1
Traceback (most recent call last):
 File "/usr/local/bin/cdqr.py", line 1585, in <module>
    main()
  File "/usr/local/bin/cdqr.py", line 1450, in main
    p_ver = plaso_version(log2timeline_location)
  File "/usr/local/bin/cdqr.py", line 884, in plaso_version
    myproc = subprocess.Popen([log2timeline_location,"--version"],stderr=subprocess.PIPE)
  File "/usr/lib/python3.5/subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.5/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'log2timeline.py'

**Comment by glennbarrett** [comment]
Forgot to note that I had run the update.sh script before trying this.  Not sure if that affected it.

**Comment by rough007** [comment]
Glenn,

Thanks for bringing this up.  I'm not able to test for the next couple of days but I will later this week.  My guess is that something happened with with plaso apt-get repo and that they are in the process of updating it therefore all of the dependencies aren't aligning at this time.  I recommend rolling back to a snapshot of the VM before the update script was run or redeploying the OVF and not running the update.sh script until the Plaso repository is fixed (usually takes a couple to a few days).  

Checking the Plaso git it looks like they are in the middle of updating the Linux repo's.  https://github.com/log2timeline/plaso/issues/1421

**Comment by rough007** [comment]
The work around for now is to comment out the following lines of the update.sh script

echo "Updating OS"
sudo apt-get -y update
sudo apt-get -y dist-upgrade
sudo apt-get -y autoremove

**Comment by rough007** [comment]
Filed an issue with Plaso Github for upgrading:
https://github.com/log2timeline/plaso/issues/1484

**Comment by rough007** [comment]
This is not officially supported yet in CDQR but that support is coming.

## The final upgrade script for CCF-VM 2.x is:
```
sudo add-apt-repository -y universe
sudo add-apt-repository -y ppa:gift/stable
sudo apt -y purge python-artifacts python3-artifacts plaso plaso-data plaso-tools python-plaso forensics-all
sudo rm -rf /usr/lib/python2.7/dist-packages/plaso
sudo apt -y -f install
sudo apt -y autoremove
sudo apt -y autoclean
sudo -H pip uninstall PyYAML
sudo -H pip uninstall artifacts

sudo apt -y update;sudo apt-get -y dist-upgrade
sudo apt -y install python-plaso plaso-tools
sudo shutdown -r "now"
```
