### ISSUE TITLE
systemd[1]Failed to start Raise network interfaces.

### ISSUE THREAD

**Issue by ncgordo** [rough007/CCF-VM#4]
Imported the CCF-VM into virtualbox and attempted to start on company managed laptop.  The FW rules prevented access to the running server so had to use Virtualbox Host-Only Ethernet Adapter under Virtualbox network settings.  When the VM boots up it displayed the error "FAILED: failed to start raise network interfaces".  logged into the VM and the "ifconfig" command revealed no eth0 interface and no assigned IPV4 address.  

Resolution:
Ubuntu uses Predictable Network Interface Naming 
ifconfig -a to view the available interfaces
sudo vi /etc/network/interfaces
add the following lines:
auto enp0s17 (this was the Ethernet interface name from the ifconfig -a command)
iface enp0s17 inet dhcp

Restart resulted in interface enp0s17 being assigned a private IP address accessible from the Host system.

**Comment by rough007** [comment]
Great point thanks for bringing it up.  We did a write up on this process for our DEFCON Workshop slides 9 -11 here: https://media.defcon.org/DEF%20CON%2025/DEF%20CON%2025%20workshops/DEFCON-25-Workshop-Alan-Orlikoski-and-Dan-M-Free-and-Easy-DFIR-Triage-for-Everyone.pdf
