### ISSUE TITLE
"kopf" no longer available -> cerebro

### ISSUE THREAD

**Issue by ThetaGamma** [rough007/CCF-VM#7]
it looks as if the README and the userguide does not yet reflect the change from "kopf" to "cerebro", right?
so cluster management should be done with 

> http://\<CCF-VM IP Address or localhost\>:9000

BTW: netstat shows still a process listening on port 9200 on localhost

**Comment by rough007** [comment]
That's correct about Cerebro on port 9000.  I'll take a look at updating the readme to remove the kopf section and I'll take a look to at what is still listening on 9200.

Thanks for submitting this!

**Comment by rough007** [comment]
An update, I confirmed that 9200 is being used directly by elasticsearch and not being used by kopf.  The documentation does need to be updated to remove all mentions of kopf and the current state of things.

```
me@ccf-vm:~$ sudo lsof -i :9200
COMMAND  PID          USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
java    1437 elasticsearch  156u  IPv6  18690      0t0  TCP localhost:9200 (LISTEN)
java    1437 elasticsearch  157u  IPv6  18691      0t0  TCP localhost:9200 (LISTEN)
me@ccf-vm:~$ sudo ps aux |grep 1437
elastic+  1437  1.8  1.8 4624576 285016 ?      Ssl  11:14   0:22 /usr/bin/java -Xms256m -Xmx1g -Djava.awt.headless=true -XX:+UseParNewGC -XX:+UseConcMarkSweepGC -XX:CMSInitiatingOccupancyFraction=75 -XX:+UseCMSInitiatingOccupancyOnly -XX:+HeapDumpOnOutOfMemoryError -XX:+DisableExplicitGC -Dfile.encoding=UTF-8 -Djna.nosys=true -Des.path.home=/usr/share/elasticsearch -cp /usr/share/elasticsearch/lib/elasticsearch-2.4.4.jar:/usr/share/elasticsearch/lib/* org.elasticsearch.bootstrap.Elasticsearch start -Des.pidfile=/var/run/elasticsearch/elasticsearch.pid -Des.default.path.home=/usr/share/elasticsearch -Des.default.path.logs=/var/log/elasticsearch -Des.default.path.data=/var/lib/elasticsearch -Des.default.path.conf=/etc/elasticsearch


```
